import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ProviderWrapper from "@/components/ProviderWrapper/ProviderWrapper";




export const metadata: Metadata = {
    title: "Migmag",
    description: "Generated by bd calling it.",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                suppressHydrationWarning
                className={` antialiased`}
            >

                <main className={` w-full `} >
                    <ProviderWrapper>
                        {
                            children
                        }
                    </ProviderWrapper>
                </main>
            </body>
        </html>
    );
}
